import time
from typing import TypedDict
import yaml
from langgraph.graph import StateGraph, START, END

from langchain_ollama import ChatOllama
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

# --- Configuration ---
with open("../config.yaml", "r") as f:
    config = yaml.safe_load(f)

DB_PATH = config['database']['path']
K = config['database']['k_retrieval']
MODEL_NAME = config['models']['llm_name']
EMBEDDING_NAME = config['models']['embedding_name']
DEVICE = config['models']['device']
LLM_TEMPERATURE = config['models']['llm_temperature']

# --- Global Initialization ---
print("Initializing models and warming up GPU...")
embedding_model = HuggingFaceEmbeddings(
    model_name=EMBEDDING_NAME,
    model_kwargs={'device': DEVICE}
)
vectorstore = Chroma(persist_directory=DB_PATH, embedding_function=embedding_model)

llm = ChatOllama(model=MODEL_NAME, temperature=LLM_TEMPERATURE)

# WARM UP THE LLM
print("Sending warm-up ping to Ollama...")
llm.invoke("Hi")
print("GPU is warm. Ready to benchmark.")


# --- 1. Define the State ---
class AgentState(TypedDict):
    question: str  # The original question
    question_id: str  # Required for strict Distractor retrieval
    plan: str  # The step-by-step plan generated by the Planner
    context: str  # The retrieved documents
    answer: str  # The final answer


# --- Node 1: The Planner ---
def planner_node(state: AgentState):
    print("--- 🧠 PLANNER: Breaking down the task ---")

    template = """You are a Planner Agent.
    Break down the following complex question into a clear, step-by-step search plan.
    Do not answer the question. Just list the steps required to find the answer.

    Question: {question}

    Plan:"""
    prompt = ChatPromptTemplate.from_template(template)
    chain = prompt | llm | StrOutputParser()

    plan = chain.invoke({"question": state["question"]})
    print(f"Generated Plan:\n{plan}\n")

    return {"plan": plan}


# --- Node 2: The Performer (Enhanced RAG) ---
def performer_node(state: AgentState):
    print("--- 🏃 PERFORMER: Executing RAG ---")

    # Retrieve Context using Metadata Filtering
    retriever = vectorstore.as_retriever(
        search_kwargs={
            "k": K,
            "filter": {"question_id": state["question_id"]}
        }
    )

    docs = retriever.invoke(state["question"])
    context_text = "\n\n".join(doc.page_content for doc in docs)

    # Generate Answer
    template = """You are an Expert Performer. 
    Execute the following plan to answer the question using the provided context.

    Plan:
    {plan}

    Context:
    {context}

    Question: {question}

    Answer:"""

    prompt = ChatPromptTemplate.from_template(template)
    chain = prompt | llm | StrOutputParser()

    answer = chain.invoke({
        "plan": state["plan"],
        "context": context_text,
        "question": state["question"]
    })

    return {"answer": answer, "context": context_text}


# --- Build the Graph ---
def build_linear_agent():
    workflow = StateGraph(AgentState)

    workflow.add_node("planner", planner_node)
    workflow.add_node("performer", performer_node)

    workflow.add_edge(START, "planner")
    workflow.add_edge("planner", "performer")
    workflow.add_edge("performer", END)

    return workflow.compile()


# Compile the agent globally so graph construction isn't timed
linear_agent = build_linear_agent()


# --- Execution Wrapper ---
def run_linear_agent(question: str, question_id: str):
    """
    Executes the linear agent workflow and records latency.
    """
    print(f"\n--- Processing Question: {question} ---")

    start_time = time.time()

    # Invoke the graph with both required inputs
    result = linear_agent.invoke({
        "question": question,
        "question_id": question_id
    })

    end_time = time.time()
    latency = end_time - start_time

    print(f"Answer: {result['answer']}")
    print(f"⏱️ Total Latency: {latency:.2f} seconds")

    return result['answer'], latency


if __name__ == "__main__":
    run_linear_agent("Were Scott Derrickson and Ed Wood of the same nationality?", "5a8b57f25542995d1e6f1371")
