import time
from typing import TypedDict, List
from langgraph.graph import StateGraph, START, END

from langchain_ollama import ChatOllama
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

# --- Configuration ---
DB_PATH = "./vectorstore"
MODEL_NAME = "llama3.1"


# 1. Define the State
# This is the "Shared Memory" that gets passed between agents.
class AgentState(TypedDict):
    question: str  # The original user question
    plan: str  # The step-by-step plan generated by the Planner
    context: str  # The retrieved documents
    answer: str  # The final answer
    latency: float  # To track performance


# --- Node 1: The Planner ---
def planner_node(state: AgentState):
    print("--- 🧠 PLANNER: Breaking down the task ---")

    llm = ChatOllama(model=MODEL_NAME, temperature=0)

    # Prompt the LLM to think before acting
    template = """You are a Planner Agent.
    Break down the following complex question into a clear, step-by-step search plan.
    Do not answer the question. Just list the steps required to find the answer.

    Question: {question}

    Plan:"""
    prompt = ChatPromptTemplate.from_template(template)
    chain = prompt | llm | StrOutputParser()

    # Execute
    plan = chain.invoke({"question": state["question"]})
    print(f"Generated Plan:\n{plan}\n")

    # Update State
    return {"plan": plan}


# --- Node 2: The Performer (Enhanced RAG) ---
def performer_node(state: AgentState):
    print("--- 🏃 PERFORMER: Executing RAG ---")

    # Setup standard tools
    embedding_model = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
    vectorstore = Chroma(persist_directory=DB_PATH, embedding_function=embedding_model)
    retriever = vectorstore.as_retriever(search_kwargs={"k": 3})  # Increased k slightly for complex plans
    llm = ChatOllama(model=MODEL_NAME, temperature=0)

    # 1. Retrieve Context (using the Plan to guide search is advanced,
    # for now we use the Question but the Answer is guided by the Plan)
    # Note: In advanced agents, we might generate specific queries from the plan.
    docs = retriever.invoke(state["question"])
    context_text = "\n\n".join(doc.page_content for doc in docs)

    # 2. Generate Answer
    template = """You are an Expert Performer. 
    Execute the following plan to answer the question using the provided context.

    Plan:
    {plan}

    Context:
    {context}

    Question: {question}

    Answer:"""

    prompt = ChatPromptTemplate.from_template(template)
    chain = prompt | llm | StrOutputParser()

    answer = chain.invoke({
        "plan": state["plan"],
        "context": context_text,
        "question": state["question"]
    })

    return {"answer": answer, "context": context_text}


# --- Build the Graph ---
def build_linear_agent():
    workflow = StateGraph(AgentState)

    # Add Nodes
    workflow.add_node("planner", planner_node)
    workflow.add_node("performer", performer_node)

    # Add Edges (The Logic)
    workflow.add_edge(START, "planner")
    workflow.add_edge("planner", "performer")
    workflow.add_edge("performer", END)

    # Compile
    return workflow.compile()


# --- Execution & Measurement ---
if __name__ == "__main__":
    agent = build_linear_agent()

    question = "Why do agentic workflows introduce latency?"
    print(f"Processing: {question}")

    start_time = time.time()

    # Run the Graph
    result = agent.invoke({"question": question})

    end_time = time.time()
    total_latency = end_time - start_time

    print(f"\nFinal Answer: {result['answer']}")
    print(f"⏱️ Total Latency: {total_latency:.2f} seconds")